### ISSUE TITLE
How to set BuildList in Monster.ini

### ISSUE THREAD

**Issue by jack6th** [heavenchou/Monster#1]
There is no index/buildlist.txt in the bookcase_v055_20200827.zip   
I try to set it to index/../spine.txt and it does not work.

**Comment by heavenchou** [comment]
我英文很差，希望你能看懂中文。

這個程式是2016之前的版本，若您有 CBETA 2016 的資料，就可以看到 buildlist.txt，這和現在的版本有一點不同。

bulidlist.txt 長的像這樣，目錄名稱沒有影響。

19280
D:\index_b5\T\T01\T0001_001.txt
D:\index_b5\T\T01\T0001_002.txt
D:\index_b5\T\T01\T0001_003.txt
D:\index_b5\T\T01\T0001_004.txt
D:\index_b5\T\T01\T0001_005.txt
.......

**Comment by jack6th** [comment]
由於在CBReader v056的源碼中並沒有Monster部分的源碼（好像和這個Monster不太一樣），能否解釋一下bookcase_v055_20200827.zip中index/main.ndx的結構。
